### ISSUE TITLE
There is only one SAMS  layer when ap_level = 2?

### ISSUE THREAD

**Issue by hiyijian** [CHENGY12/APNet#1]
There is only one SAMS  layer when ap_level = 2 accoding to baseline.py. Is that consistent with paper?

**Comment by CHENGY12** [comment]
Thanks for your attention to our work.  "AP_level =2" denotes that the attention pyramid has both level-1 attention and level-2 attention. It is worth noting that the level-1 attention is the baseline global attention model (e.g. SE attention in the channel-wise model). Only level-2 attention needs a SAMS module to split and merge. It is consistent with our paper (e.g. we write “APNet-C1 only has a global attention map“on page 8). Please see the  "Ablation Studies" part for more details. 
Please do not hesitate to contact me if you have any additional questions.

**Comment by hiyijian** [comment]
Thanks for your reply.  I noticed that APNet-C1 slightly outperforms SE-ResNet accodding to TABLE 2 in your paper. It was a little unexpected for me, since APNet-C1 has quite fewer SELayer with different location(after f(x) + x). What do you think about this, please?

**Comment by CHENGY12** [comment]
Personally, I think APNet-C1 and SE-ResNet are comparable. It may be because the number of attention layers in APNet-C1 is enough for Person ReID (Market and Duke).  In our experiments, we don't find a consistent law between the number of attention layers and ReID performance.

**Comment by hiyijian** [comment]
It seems that SELayer takes no effects. Please see https://github.com/CHENGY12/APNet/blob/74efb126abdb98ce2fc69ef54eb9d08aa6be8eb9/modeling/backbones/se_resnet.py#L76

**Comment by CHENGY12** [comment]
Thank you very much for pointing out this！We have fixed this. It is a typo that occurs when we cleaned the code and released it for git. We only checked the APNet but ignored to check this. This typo has no influence on the conclusions in the paper because it is only in this repo but not in our experiments. Thank you again for helping us find this typo. Please let me know if you have any other questions.
