### ISSUE TITLE
APNet算法中cuhk03测试结果问题

### ISSUE THREAD

**Issue by pingooooo** [CHENGY12/APNet#10]
针对cuhk03这个数据集，我一直跑不出您论文给出的结果，想请问下当时您对于该数据集的参数是怎么设置的。举个例子：论文中cuhk03(l):mAP 85.3%; R-1 87.4% ，我测试的结果是 mAP 77.8%; R-1 80.9%。

**Comment by hamed-508** [comment]
Hello. Is the accuracy reported in the article the best accuracy? Because every time the network is trained, the accuracies are slightly different

**Comment by pingooooo** [comment]
啦啦啦，亲，来信已收到，我会尽快看您的来信哈，(●'?7?0'●)

**Comment by pingooooo** [comment]
> Hello. Is the accuracy reported in the article the best accuracy? Because every time the network is trained, the accuracies are slightly different

Hello, I'm not the author of this article and I can't run the results in the article, maybe there are special settings for those dataset parameters, etc. that are not mentioned in the article

**Comment by CHENGY12** [comment]
Hi guys, thanks for your interests and discussions!  This released code is not included the cuhk part (including multi-part tricks).  It is reasonable that the performance is lower than the reported ones. 

As mentioned in the paper,
> We find that the multi-part trick in MGN [31] is very effective on the CUHK03 dataset. The multi-part trick adds a new local branch which splits the feature map into two parts and learns the local features. Specifically, the feature maps are split from the third residual block along the height dimension. In the inference, we connected the original global feature with local features for final matching. However, the effectiveness of this trick is limited when we add the scale of datasets (e.g., MSMT17 [11] or Market-1501 [8]). Thus, we only use the mutli-part trick on the CUHK03 dataset, but not on other datasets.


If you would like to obtain a better performance on CUHK, please add an extra multi-part trick in MGN [31].  This trick works well on CUHK but not for others.

**Comment by pingooooo** [comment]
啦啦啦，亲，来信已收到，我会尽快看您的来信哈，(●'?7?0'●)
