### ISSUE TITLE
The map of the datasets MSMT is different from that in the paper

### ISSUE THREAD

**Issue by zcgit001** [CHENGY12/APNet#2]
Hi,
Thanks for sharing the code!!!
I run the experiments on Matket and Duke, and the results are similar to that in your paper. But the experiment result of MSMT is different from that in your paper. The map and rank1 of MSMT are 58.7% and 80.4% in my experiment. But, in your paper, the map and rank1 of MSMT are 63.5% and 83.7%. Maybe the experiment setup on MSMT is different from other datasets？

**Comment by CHENGY12** [comment]
Thanks for your attention!
The config and code in this repo were only for Market and Duke. The config for MSMT17 is available in the repo, now. Please let me know if you have any additional questions.

**Comment by zcgit001** [comment]
Thanks for your reply!
Another question.In your paper, the baseline without any attention on Market is map 87.8% and rank1 95.0%. But the results on Market of paper bag of tricks  are map 85.9% and rank1 94.5%. Why is your baseline so much higher than the paper bag of tricks? I modified the image size and lr in your code to the same as paper bag of tricks [256,128] and 0.00035, and your result is still much higher than the paper bag of tricks.I haven't found the part of your code that causes this result for the time being.

**Comment by CHENGY12** [comment]
Please check the configs and paper for details. We modify some hyper-parameters and add some tricks for better performance.
I guess it may be because of the horizontal flip inference (may be useful for mAP), better batch size (may be useful for R1), and other hyper-parameters. 
Hope you find it helpful.

**Comment by zcgit001** [comment]
Thanks! I will check the configs and paper carefully.
Thanks again for your reply.
