### ISSUE TITLE
Generate a test image that corresponds to that part of the code.

### ISSUE THREAD

**Issue by 1691077362** [CHENGY12/APNet#3]
Hi,
Thanks for sharing the code!!!
Why did I test with MSMT17 and only get map data, but not the generated images.
Generate a test image that corresponds to that part of the code.

**Comment by 1691077362** [comment]
你好，
感谢分享代码！！！
为什么我用msmt17进行测试最后只得到了map数据，而没有得到生成的图片。
还有就是生成测试后的图片，对应着那部分的代码。 @ @CHENGY12

**Comment by CHENGY12** [comment]
Thanks for your interest in our paper. 
APNet is a discriminative model for the person ReID task. Given a benchmark (including MSMT), APNet extracts the features of both query and gallery images and matches them for evaluation. This evaluation process is not related to image generation.   The details can be found in the [paper](https://arxiv.org/pdf/2108.05340.pdf).  Hope you find it helpful.

**Comment by 1691077362** [comment]
不好意思我可能能没表达清楚，我想要的是数据可视化的代码。

**Comment by 1691077362** [comment]
具有不同金字塔级别的注意力图的可视化。我们采用 Grad-CAM 来可视化我们的注意力金字塔的学习注意力图。

**Comment by 1691077362** [comment]
@CHENGY12  Can you share the code for your visualization part? I really won't, thanks

**Comment by Gutianpei** [comment]
> @CHENGY12 Can you share the code for your visualization part? I really won't, thanks

Hello,

As mentioned in our paper, we used Grad-CAM to visualize the attention map. Please consider using the open-source implementation of Grad-CAM such as https://github.com/jacobgil/pytorch-grad-cam.

**Comment by 1691077362** [comment]
@Gutianpei thank you
