### ISSUE TITLE
the code of spatial attention

### ISSUE THREAD

**Issue by trouble-killer** [CHENGY12/APNet#8]
Hi,
Thanks for sharing the code！
I`m curious about the code of spatial attention(APNet-S). Would you mind sharing it, and this is my email address if it's convenient，1127163106@qq.com

**Comment by Gutianpei** [comment]
Hello, 

Unfortunately we are not able to provide codes for spatial attention. We use [RGA-S](https://github.com/microsoft/Relation-Aware-Global-Attention-Networks) as spatial attention. You can either implement APNet in their RGA-S repo or transfer RGA-S code to this repo. We tested both methods and the results are similar. Hope this helps.
